# #################################################################################
# idaes-sdoe is part of the IDAES integrated software platform, specifically
# the Institute for the Design of Advanced Energy Systems Process Systems
# Engineering Framework (IDAES PSE Framework).
#
# Copyright (c) 2018-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory,
# National Technology & Engineering Solutions of Sandia, LLC, Carnegie Mellon
# University, West Virginia University Research Corporation, et al.
# All rights reserved. Please see the files COPYRIGHT.md and LICENSE.md
# for full copyright and license information.
# #################################################################################
from __future__ import annotations

from typing import Iterable

import pandas as pd

from .exceptions import ConfigurationError, DataValidationError
from .io import align_previous_to_candidate
from .models import ColumnRoles, DesignSetup
from .scaling import build_bounds


def _ensure_columns(frame: pd.DataFrame, columns: Iterable[str], label: str) -> None:
    """Raise if a table is missing required columns.

    Args:
        frame: Table to validate.
        columns: Required column names.
        label: Human-readable table label for error messages.
    """
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        joined = ", ".join(missing)
        raise DataValidationError(f"{label} is missing required columns: {joined}.")


def _ensure_numeric(frame: pd.DataFrame, columns: Iterable[str], label: str) -> None:
    """Raise if required columns are not numeric.

    Args:
        frame: Table to validate.
        columns: Columns that must be numeric.
        label: Human-readable table label for error messages.
    """
    invalid = [column for column in columns if not pd.api.types.is_numeric_dtype(frame[column])]
    if invalid:
        joined = ", ".join(invalid)
        raise DataValidationError(f"{label} must be numeric: {joined}.")


def _add_index_if_needed(
    candidate: pd.DataFrame,
    previous: pd.DataFrame | None,
    roles: ColumnRoles,
    index_column: str,
) -> tuple[pd.DataFrame, pd.DataFrame | None, ColumnRoles]:
    """Insert an autogenerated index column when none is provided.

    Args:
        candidate: Candidate table.
        previous: Optional previous-data table.
        roles: Current column-role configuration.
        index_column: Name of the generated index column.

    Returns:
        Candidate table, previous-data table, and updated roles with the index
        column populated.
    """
    if roles.index:
        return candidate, previous, roles

    candidate_out = candidate.copy()
    candidate_out.insert(0, index_column, range(len(candidate_out)))

    previous_out = None
    if previous is not None:
        previous_out = previous.copy()
        previous_out.insert(0, index_column, range(len(candidate_out), len(candidate_out) + len(previous_out)))

    return candidate_out, previous_out, ColumnRoles(
        index=index_column,
        inputs=roles.inputs,
        responses=roles.responses,
        weight=roles.weight,
    )


def prepare_design_setup(
    *,
    candidate: pd.DataFrame,
    roles: ColumnRoles,
    previous: pd.DataFrame | None = None,
    bounds: dict[str, tuple[float, float]] | None = None,
    auto_index: bool = True,
    index_column: str = "__id",
) -> DesignSetup:
    """Validate design inputs and build a reusable setup object.

    Args:
        candidate: Candidate table used to construct designs.
        roles: Column-role assignment for the workflow.
        previous: Optional previous-data table.
        bounds: Optional explicit scaling bounds.
        auto_index: If ``True``, add an index column when one is not supplied.
        index_column: Name to use for an autogenerated index column.

    Returns:
        Validated design setup containing aligned tables, roles, and bounds.
    """
    candidate_frame = candidate.copy()
    previous_frame = previous.copy() if previous is not None else None

    if previous_frame is not None:
        previous_frame = align_previous_to_candidate(candidate_frame, previous_frame)

    if auto_index:
        candidate_frame, previous_frame, roles = _add_index_if_needed(
            candidate_frame, previous_frame, roles, index_column
        )

    included = roles.included_columns()
    if not roles.inputs:
        raise ConfigurationError("At least one input column is required.")

    _ensure_columns(candidate_frame, included, "Candidate table")
    _ensure_numeric(candidate_frame, roles.inputs + roles.responses + ([roles.weight] if roles.weight else []), "Candidate table")

    if previous_frame is not None:
        _ensure_columns(previous_frame, included, "Previous-data table")
        _ensure_numeric(previous_frame, roles.inputs + roles.responses + ([roles.weight] if roles.weight else []), "Previous-data table")

    used_bounds = build_bounds(candidate_frame, previous_frame, included, bounds)
    return DesignSetup(candidate=candidate_frame, previous=previous_frame, roles=roles, bounds=used_bounds)
